IF(DEFINED HDF5_DIR)
    MESSAGE(STATUS "Using user defined variable HDF5_DIR = ${HDF5_DIR}")
    FIND_PACKAGE(HDF5 PATHS ${HDF5_DIR} NO_SYSTEM_ENVIRONMENT_PATH)
ELSEIF(DEFINED ENV{HDF5_ROOT})
    MESSAGE(STATUS "Using environnment defined variable HDF5_ROOT = $ENV{HDF5_ROOT}")
    FIND_PACKAGE(HDF5 PATHS $ENV{HDF5_ROOT}/cmake/hdf5 NO_CMAKE_PATH NO_SYSTEM_ENVIRONMENT_PATH)
ELSE()
    FIND_PACKAGE(HDF5)
ENDIF()

# NO_CMAKE_PATH
# NO_SYSTEM_ENVIRONMENT_PATH
# NO_CMAKE_PACKAGE_REGISTRY
# NO_CMAKE_BUILDS_PATH
# NO_CMAKE_SYSTEM_PATH
# NO_CMAKE_SYSTEM_PACKAGE_REGISTRY

IF(HDF5_FOUND)
    MESSAGE(STATUS "HDF5                     : ${HDF5}")
    MESSAGE(STATUS "HDF5_INCLUDE_DIR         : ${HDF5_INCLUDE_DIR}")
    MESSAGE(STATUS "HDF5_INCLUDE_DIR_FORTRAN : ${HDF5_INCLUDE_DIR_FORTRAN}")
    MESSAGE(STATUS "HDF5_INCLUDE_DIRS        : ${HDF5_INCLUDE_DIRS}")
    MESSAGE(STATUS "HDF5_VERSION_STRING      : ${HDF5_VERSION_STRING}")
    MESSAGE(STATUS "HDF5_VERSION_MAJOR       : ${HDF5_VERSION_MAJOR}")
    MESSAGE(STATUS "HDF5_VERSION_MINOR       : ${HDF5_VERSION_MINOR}")
    MESSAGE(STATUS "HDF5_ENABLE_PARALLEL     : ${HDF5_ENABLE_PARALLEL}")
    MESSAGE(STATUS "HDF5_BUILD_FORTRAN       : ${HDF5_BUILD_FORTRAN}")
    MESSAGE(STATUS "HDF5_BUILD_CPP_LIB       : ${HDF5_BUILD_CPP_LIB}")
    MESSAGE(STATUS "HDF5_BUILD_TOOLS         : ${HDF5_BUILD_TOOLS}")
    MESSAGE(STATUS "HDF5_BUILD_HL_LIB        : ${HDF5_BUILD_HL_LIB}")
    MESSAGE(STATUS "HDF5_BUILD_HL_CPP_LIB    : ${HDF5_BUILD_HL_CPP_LIB}")
    MESSAGE(STATUS "HDF5_USE_STATIC_LIBRARIES          - Static or dynamic library                                 : " ${HDF5_USE_STATIC_LIBRARIES})
    MESSAGE(STATUS "HDF5_INCLUDE_DIRS                  - Location of the hdf5 includes                             : " ${HDF5_INCLUDE_DIRS})
    MESSAGE(STATUS "HDF5_DEFINITIONS                   - Required compiler definitions for HDF5                    : " ${HDF5_DEFINITIONS})
    MESSAGE(STATUS "HDF5_C_LIBRARIES                   - Required libraries for the HDF5 C bindings.               : " ${HDF5_C_LIBRARIES})
    MESSAGE(STATUS "HDF5_CXX_LIBRARIES                 - Required libraries for the HDF5 C++ bindings              : " ${HDF5_CXX_LIBRARIES})
    MESSAGE(STATUS "HDF5_Fortran_LIBRARIES             - Required libraries for the HDF5 Fortran bindings          : " ${HDF5_Fortran_LIBRARIES})
    MESSAGE(STATUS "HDF5_HL_LIBRARIES                  - Required libraries for the HDF5 high level API            : " ${HDF5_HL_LIBRARIES})
    MESSAGE(STATUS "HDF5_Fortran_HL_LIBRARIES          - Required libraries for the high level Fortran bindings.   : " ${HDF5_Fortran_HL_LIBRARIES})
    MESSAGE(STATUS "HDF5_LIBRARIES                     - Required libraries for all requested bindings             : " ${HDF5_LIBRARIES})
    MESSAGE(STATUS "HDF5_LIBRARY_DIRS                  - The full set of library directories                       : " ${HDF5_LIBRARY_DIRS})
    MESSAGE(STATUS "HDF5_IS_PARALLEL                   - Whether or not HDF5 was found with parallel IO support    : " ${HDF5_IS_PARALLEL})
    MESSAGE(STATUS "HDF5_C_COMPILER_EXECUTABLE         - The path to the HDF5 C wrapper compiler                   : " ${HDF5_C_COMPILER_EXECUTABLE})
    MESSAGE(STATUS "HDF5_CXX_COMPILER_EXECUTABLE       - The path to the HDF5 C++ wrapper compiler                 : " ${HDF5_CXX_COMPILER_EXECUTABLE})
    MESSAGE(STATUS "HDF5_Fortran_COMPILER_EXECUTABLE   - The path to the HDF5 Fortran wrapper compiler             : " ${HDF5_Fortran_COMPILER_EXECUTABLE})
    MESSAGE(STATUS "HDF5_DIFF_EXECUTABLE               - The path to the HDF5 dataset comparison tool              : " ${HDF5_DIFF_EXECUTABLE})

    MESSAGE(STATUS "hdf5              : HDF5 C library                                                             : " ${hdf5})
    MESSAGE(STATUS "hdf5_tools        : the tools library                                                          : " ${hdf5_tools})
    MESSAGE(STATUS "hdf5_f90cstub     : used by Fortran to C interface                                             : " ${hdf5_f90cstub})
    MESSAGE(STATUS "hdf5_fortran      : Fortran HDF5 library                                                       : " ${hdf5_fortran})
    MESSAGE(STATUS "hdf5_cpp          : HDF5 cpp interface library                                                 : " ${hdf5_cpp})
    MESSAGE(STATUS "hdf5_hl           : High Level library                                                         : " ${hdf5_hl})
    MESSAGE(STATUS "hdf5_hl_f90cstub  : used by Fortran to C interface to High Level library                       : " ${hdf5_hl_f90cstub})
    MESSAGE(STATUS "hdf5_hl_fortran   : Fortran High Level library                                                 : " ${hdf5_hl_fortran})
    MESSAGE(STATUS "hdf5_hl_cpp       : High Level cpp interface library                                           : " ${hdf5_hl_cpp})
    MESSAGE(STATUS "HDF5_ROOT_DIR_HINT                                                                             : " ${HDF5_ROOT_DIR_HINT})
    MESSAGE(STATUS "CMAKE_Fortran_MODULE_DIRECTORY                                                                 : " ${CMAKE_Fortran_MODULE_DIRECTORY})
    MESSAGE(STATUS "LIB_TYPE                                                                                       : " ${LIB_TYPE})

    IF(NOT EXISTS ${HDF5_INCLUDE_DIR_FORTRAN})
        SET(HDF5_INCLUDE_DIR_FORTRAN ${HDF5_INCLUDE_DIR})
    ENDIF()
ELSE()
    MESSAGE(STATUS "HDF5 NOT FOUND")
ENDIF()

