# Please note that the find_package invocation
# changed in HDF5-1.8.16 to require "shared" or "static"
SET(FIND_HDF_COMPONENTS C HL CXX CXX_HL)
IF(DEFINED HDF5_DIR)
    MESSAGE(STATUS "Using user defined variable HDF5_DIR = ${HDF5_DIR}")
    FIND_PACKAGE(HDF5 PATHS ${HDF5_DIR} NO_SYSTEM_ENVIRONMENT_PATH COMPONENTS ${FIND_HDF_COMPONENTS} NO_MODULE REQUIRED static)
ELSEIF(DEFINED ENV{HDF5_ROOT})
    MESSAGE(STATUS "Using environnment defined variable HDF5_ROOT = $ENV{HDF5_ROOT}")
    FIND_PACKAGE(HDF5 PATHS $ENV{HDF5_ROOT}/cmake/hdf5 NO_CMAKE_PATH NO_SYSTEM_ENVIRONMENT_PATH COMPONENTS ${FIND_HDF_COMPONENTS} NO_MODULE REQUIRED static)
ELSE()
    FIND_PACKAGE(HDF5 COMPONENTS ${FIND_HDF_COMPONENTS} NO_MODULE REQUIRED static)
ENDIF()

# NO_CMAKE_PATH
# NO_SYSTEM_ENVIRONMENT_PATH
# NO_CMAKE_PACKAGE_REGISTRY
# NO_CMAKE_BUILDS_PATH
# NO_CMAKE_SYSTEM_PATH
# NO_CMAKE_SYSTEM_PACKAGE_REGISTRY

IF(HDF5_FOUND)

    IF(NOT HDF5_C_STATIC_LIBRARY)
        SET(HDF5_C_STATIC_LIBRARY hdf5)
    ENDIF()
    IF(NOT HDF5_CXX_STATIC_LIBRARY)
        SET(HDF5_CXX_STATIC_LIBRARY hdf5_cpp)
    ENDIF()

    MESSAGE(STATUS "HDF5_INCLUDE_DIR         : ${HDF5_INCLUDE_DIR}")
    MESSAGE(STATUS "HDF5_INCLUDE_DIR_FORTRAN : ${HDF5_INCLUDE_DIR_FORTRAN}")
    MESSAGE(STATUS "HDF5_INCLUDE_DIRS        : ${HDF5_INCLUDE_DIRS}")
    MESSAGE(STATUS "HDF5_LIBRARIES           : ${HDF5_LIBRARIES}")
    MESSAGE(STATUS "HDF5_VERSION_STRING      : ${HDF5_VERSION_STRING}")
    MESSAGE(STATUS "HDF5_ENABLE_PARALLEL     : ${HDF5_ENABLE_PARALLEL}")
    MESSAGE(STATUS "HDF5_BUILD_FORTRAN       : ${HDF5_BUILD_FORTRAN}")
    MESSAGE(STATUS "HDF5_BUILD_CPP_LIB       : ${HDF5_BUILD_CPP_LIB}")
    MESSAGE(STATUS "HDF5_BUILD_HL_LIB        : ${HDF5_BUILD_HL_LIB}")
    MESSAGE(STATUS "HDF5_BUILD_HL_CPP_LIB    : ${HDF5_BUILD_HL_CPP_LIB}")
    MESSAGE(STATUS "HDF5_C_STATIC_LIBRARY    : ${HDF5_C_STATIC_LIBRARY}")
    MESSAGE(STATUS "HDF5_CXX_STATIC_LIBRARY  : ${HDF5_CXX_STATIC_LIBRARY}")
    IF(NOT EXISTS ${HDF5_INCLUDE_DIR_FORTRAN})
        SET(HDF5_INCLUDE_DIR_FORTRAN ${HDF5_INCLUDE_DIR})
    ENDIF()
ELSE()
    MESSAGE(STATUS "HDF5 NOT FOUND")
ENDIF()

