IF(MINGW)
    SET(PROTOBUF_LIBPROTOBUF /opt/ProtoBuf/lib/libprotobuf.a)
    SET(PROTOBUF_PROTOC wine /opt/ProtoBuf/bin/protoc.exe-3.7.0.0)
    SET(PROTOC_PREFIX "Z:")
    SET(PROTOBUF_INCLUDE_DIR /opt/ProtoBuf/include)
ELSE()
    SET(PROTOBUF_LIBPROTOBUF /usr/lib/x86_64-linux-gnu/libprotobuf.a)
    SET(PROTOBUF_PROTOC protoc)
    SET(PROTOC_PREFIX "")
    SET(PROTOBUF_INCLUDE_DIR /usr/include)
ENDIF()
